name: Build and Push Docker Image

on:
  push:
    branches:
      - release/stage
      - release/prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Build the Docker image
      - name: Build Docker Image
        run: |
          # Extract the last part of the branch name (after the last '/')
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | awk -F'/' '{print $NF}')
          
          # Check if the push is a Git tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version="${BRANCH_NAME}-${{ github.ref_name }}"
          else
            version="${BRANCH_NAME}"
          fi
    
          - name: Push Docker Image
            run: |
              docker push itsbijaya/git-repo:${version}
